[package]
name = "htmlvidiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5tokenizer = "0.5.2"
itertools = "0.12.0"
once_cell = "1.18.0"
regex = "1.10.2"
similar = "2.3.0"
